
spring:
  application:
    name: ribbon-consumer
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
#      defaultZone: http://peer1:1111/eureka/,http://peer2:1112/eureka/
      defaultZone: http://${eureka.instance.hostname}:1111/eureka/
server:
  port: 9000