spring:
  application:
    name: eureka-server
server:
  port: 1112
eureka:
  instance:
    hostname: peer2
  client:
    #禁止自己当做服务注册
    register-with-eureka: true
    #屏蔽注册信息,不检索服务
    fetch-registry: true
    service-url:
      defaultZone: http://peer1:1111/eureka/
