server:
  port: 8002
spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dzzdsjdb?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Dzzdsj1991
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dzzdsj.demo.springcloud2020.entity
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://erueka7001.com:7001/eureka,http://erueka7002.com:7002/eureka
#      client端用下面这种写法会注册不上。但server端这么配似乎没影响
#      default-zone: http://localhost:7001/eureka

