server:
  port: 80
spring:
  application:
    name: cloud-order-service
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://erueka7001.com:7001/eureka,http://erueka7002.com:7002/eureka
#      defaultZone: http://localhost:7001/eureka
#      client端用下面这种写法会注册不上。但server端这么配似乎没影响
#      default-zone: http://localhost:7001/eureka