server:
  port: 7002
eureka:
  instance:
    hostname: erueka7002.com
  client:
    #只维护服务实例，不检索服务
    fetch-registry: false
    #不向注册中心注册自己
    register-with-eureka: false
    service-url:
      defaultZone: http://erueka7001.com:7001/eureka
#hosts
#127.0.0.1       erueka7001.com
#127.0.0.1       erueka7002.com