logging:
  file:
    name: BookWorm.log
    path: /Users/dzzdsj/tmp/logs/springbootdemo
#    path: D:/logs/springbootdemo
  level:
#    root: WARN
    root: INFO
    org:
      springframework:
        security: DEBUG
  config:
    classpath: logback-dev.xml

yml-map:
  yml-lists:
    - list1
    - list2