spring:
  datasource:
    username: dzzdsj
    password: Dzzdsj@1991
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://dev:3306/dzzdsjdb?useUnicode=true&character_set_server=utf8mb4
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.dzzdsj.demo.mybatisdemo.entity
#  config-locations: classpath:mybatis/mybatis-config.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl