spring:
  datasource:
    url: jdbc:oracle:thin:@dev:1521:dzzdsjdb
    username: dzzdsj
    password: dzzdsj
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      # 连接池最大连接数
      maximum-pool-size: 12
      # 空闲时保持最小连接数
      minimum-idle: 5
      # 空闲连接存活时间
      idle-timeout: 300000
      # 连接超时时间
      connection-timeout: 20000
      # 测试sql
      connection-test-query: select 1 from dual
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.dzzdsj.code.databasedemo.entity
